pool:
   vmImage: 'ubuntu-latest'

trigger: none
variables:
  TESTPASSWORD: $(SQLPASSWORD)

steps: 
- task: GoTool@0
  inputs:
    version: '1.22.10'

- task: Go@0
  displayName: 'Go: install gotest.tools/gotestsum'
  inputs:
    command: 'custom'
    customCommand: 'install'
    arguments: 'gotest.tools/gotestsum@latest'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  displayName: 'Go: install github.com/axw/gocov/gocov'
  inputs:
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/axw/gocov/gocov@latest'
    workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: Go@0
  displayName: 'Go: install github.com/AlekSi/gocov-xml'
  inputs:
    command: 'custom'
    customCommand: 'install'
    arguments: 'github.com/AlekSi/gocov-xml@latest'
    workingDirectory: '$(System.DefaultWorkingDirectory)'


- task: Docker@2
  displayName: 'Run SQL 2017 docker image'
  inputs:
    command: run
    arguments: '-m 2GB -e ACCEPT_EULA=1 -d --name sql2017 -p:1433:1433 -e SA_PASSWORD=$(TESTPASSWORD) mcr.microsoft.com/mssql/server:2017-latest'

- script: |
    ~/go/bin/gotestsum --junitfile testresults.xml -- -coverprofile=coverage.txt -covermode count ./...
    ~/go/bin/gocov convert coverage.txt > coverage.json
    ~/go/bin/gocov-xml < coverage.json > coverage.xml
    mkdir coverage
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'run tests'
  env:
# skipping Azure related tests due to lack of access
    SQLPASSWORD: $(SQLPASSWORD)
    SQLSERVER_DSN: $(SQLSERVER_DSN)
  continueOnError: true
- task: PublishTestResults@2
  displayName: "Publish junit-style results"
  inputs:
    testResultsFiles: 'testresults.xml'
    testResultsFormat: JUnit
    searchFolder: '$(Build.SourcesDirectory)'
    testRunTitle: 'SQL 2017 - $(Build.SourceBranchName)'
  condition: always()
  continueOnError: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura 
    pathToSources: '$(Build.SourcesDirectory)'
    summaryFileLocation: $(Build.SourcesDirectory)/**/coverage.xml
    reportDirectory: $(Build.SourcesDirectory)/**/coverage
    failIfCoverageEmpty: true
  condition: always()
  continueOnError: true
  
